[package]
name = "dange-rs"
version = "0.1.0"
authors = ["Chase McCarthy <chase@code0100fun.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
